version: '3'

services:
  sandbox-vite:
    user: '1000:1000'
    ports: ['3000:3000']
    volumes:
      - code:/src:cached

  admin-server:
    user: '1000:1000'
    ports: ['3006:4000']
    volumes:
      - code:/src:cached

  admin-server-esbuild:
    user: '1000:1000'
    volumes:
      - code:/src:cached

  admin-server-vite:
    user: '1000:1000'
    volumes:
      - code:/src:cached

  contember-cli:
    volumes:
      - code:/src:cached

  adminer:
    ports: ['3002:8080']

  api:
    ports: ['3001:4000']

  s3:
    command: 'server --address :3003 /data'
    ports: ['3003:3003']

  postgres:
    ports: ['3005:5432']

volumes:
  code:

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    code:
      alpha: "."
      beta: "volume://code"
      mode: "two-way-resolved"
      configurationBeta:
        permissions:
          defaultOwner: "id:1000"
          defaultGroup: "id:1000"